Repository ManageIQ/container-httpd, pull requests merged in 2021-03, with the labels that each got.

#54 Added labels to image build to address red hat certification failures
  Dockerfile
Labels: technical debt

#57 Send startup and runtime logs to STDOUT
  Dockerfile
Labels: enhancement

#58 Add a manifest for debugging
  Dockerfile
Labels: developer, enhancement

#59 Make the build manifest work on tags and other non-branch heads as well
  Dockerfile
Labels: enhancement
