Repository ManageIQ/container-httpd, pull requests merged in 2022-02, with the labels that each got.

#68 Switch to GitHub Actions
  .github/workflows/ci.yaml
  .travis.yml
  bin/build_container_image
Labels: developer

#69 Bump ubi to 8.5
  Dockerfile
Labels: enhancement

#72 Fix branches in forks from failing
  .github/workflows/ci.yaml
  bin/build_container_image
Labels: bug
